import { Poppins } from 'next/font/google'
import "./globals.css";

import Header from "./components/header"
import Footer from "./components/footer"
import AnimationObserverClient from "./components/utils"
const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-poppins',
});

export const metadata = {
	title: "TrueSet Concrete",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased`}>
				<Header />
				{children}
				<Footer />
				<AnimationObserverClient />
			</body>
		</html>
	);
}
